version: '3.3'
services:
  db:
   image: "postgres"
   container_name: "reddit_postgres"
   restart: "no"
   ports:
     - '5432:5432'
   expose:
     - '5432'
   volumes:
     - redditor:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
volumes:
  redditor:
